version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:2012@postgres:5432/namozvaqtlari

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 2012
    ports:
      - "5432:5432"
